services:
  - type: web
    name: preproxy-vavoo
    runtime: docker
    region: frankfurt  # oregon, frankfurt, singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: WARNING
      - key: WORKERS
        value: 2
      - key: DVR_ENABLED
        value: false
      - key: MPD_MODE
        value: legacy
      - key: PYTHONUNBUFFERED
        value: 1
      # Uncomment for API protection
      # - key: API_PASSWORD
      #   generateValue: true
    healthCheckPath: /info
    autoDeploy: true
